import { Roboto_Condensed } from "next/font/google";
import "./globals.css";

//components
import Header from "@/components/Header";

const robotoCondensed = Roboto_Condensed({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  variable: "--font-robotoCondensed",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={robotoCondensed.variable}>
        <Header />
        {children}
      </body>
    </html>
  );
}
